services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./birthdays.txt:/app/birthdays.txt
    environment:
      - DB_PATH=/app/birthdays.txt
      - EMAIL_SMTP=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USERNAME=user
      - EMAIL_PASSWORD=pass
      - EMAIL_AUTH=true
      - EMAIL_START_TLS=true
      - BIRTHDAYS_CONGRATULATES_SCHEDULER_CRON=0 0 8 * * *
      - BIRTHDAYS_REMINDERS_SCHEDULER_CRON=0 0 8 * * *
