services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./birthdays.txt:/app/birthdays.txt
    environment:
      - DB_PATH=/app/birthdays.txt
#      - BIRTHDAYS_ORIGIN=sqlite # this can be sqlite or file
#      - SQLITE_URL=jdbc:sqlite:birthdays.db
#      - SQLITE_USERNAME=admin
#      - SQLITE_PASSWORD=admin
#      - EMAIL_SMTP=smtp.gmail.com
#      - EMAIL_PORT=587
#      - EMAIL_FROM=foobar20232@gmail.com
#      - EMAIL_USERNAME=foobar20232@gmail.com
#      - EMAIL_PASSWORD=xjncrabdxdyiwgzt
#      - EMAIL_AUTH=true
#      - EMAIL_START_TLS=true
#      - BIRTHDAYS_CONGRATULATES_SCHEDULER_CRON=0 0 8 * * *
#      - BIRTHDAYS_REMINDERS_SCHEDULER_CRON=0 0 8 * * *
