app:
  birthdays:
    db:
      path: ${DB_PATH:birthdays.txt}
    scheduler:
      congratulate: ${BIRTHDAYS_CONGRATULATES_SCHEDULER_CRON:0 0 8 * * *}
      reminders: ${BIRTHDAYS_REMINDERS_SCHEDULER_CRON:0 0 8 * * *}
spring:
  mail:
    host: ${EMAIL_SMTP:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    from: ${EMAIL_FROM:foobar20232@gmail.com}
    username: ${EMAIL_USERNAME:foobar20232@gmail.com}
    password: ${EMAIL_PASSWORD:xjncrabdxdyiwgzt}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_AUTH:true}
          starttls:
            enable:  ${EMAIL_START_TLS:true}
